
language: c

matrix:
  include:
    - os: linux
      compiler: gcc
      dist: trusty
      sudo: false
    - os: osx
      compiler: clang

addons:
  apt:
    packages:
      - autopoint
      - intltool
      # DRM
      - libdrm-dev
      # RANDR
      - libxcb1-dev
      - libxcb-randr0-dev
      # VidMode
      - libx11-dev
      - libxxf86vm-dev
      # GeoClue2
      - libglib2.0-dev
      # GUI
      - python3

before_install: |
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    brew install gettext
    brew link --force gettext
    brew install intltool
    brew install python3
  fi

install:
  - ./bootstrap
  - mkdir "$TRAVIS_BUILD_DIR/root"
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      ./configure --prefix="$TRAVIS_BUILD_DIR/root" --enable-drm --enable-vidmode --enable-randr --enable-geoclue2 --enable-gui
    elif [ "$TRAVIS_OS_NAME" == "osx" ]; then
      ./configure --prefix="$TRAVIS_BUILD_DIR/root" --enable-corelocation --enable-quartz --enable-gui
    fi
  - make -j2 install
  - make -j2 distcheck

script:
  - |
    "$TRAVIS_BUILD_DIR"/root/bin/redshift -l 12:-34 -pv
  - |
    "$TRAVIS_BUILD_DIR"/root/bin/redshift -l 12:-34 -m dummy -vo
