
language: c

matrix:
  include:
    - os: linux
      compiler: gcc
      dist: trusty
      sudo: false
    - os: osx
      compiler: clang

addons:
  apt:
    packages:
      - autopoint
      - intltool
      # DRM
      - libdrm-dev
      # RANDR
      - libxcb1-dev
      - libxcb-randr0-dev
      # VidMode
      - libx11-dev
      - libxxf86vm-dev
      # GeoClue2
      - libglib2.0-dev
      # GUI
      - python3

install: |
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    brew install gettext
    brew link --force gettext
    brew install intltool
    brew install python3
  fi

script:
  - ./bootstrap
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      ./configure --enable-drm --enable-vidmode --enable-randr --enable-geoclue2 --enable-gui
    elif [ "$TRAVIS_OS_NAME" == "osx" ]; then
      ./configure --enable-corelocation --enable-quartz --enable-gui
    fi
  - make -j2 distcheck
